configs:
- id: SYNTHETIC_TEST-7DA248BDCDC7D1BA
  config:
    name: staging_astroshop
    parameters:
      applicationweb__APPLICATION81486CD960C894C9__id:
        configId: webapp_astronomyshop
        configType: application-web
        property: id
        type: reference
      location: 
        configId: SYNTHETIC_LOCATION-1
        configType: synthetic-location
        property: id
        type: reference
      extractedIDs:
        type: value
        value:
          id_SYNTHETIC_TEST_STEP_0D7EF9ADF274202D: SYNTHETIC_TEST_STEP-0D7EF9ADF274202D
          id_SYNTHETIC_TEST_STEP_3C1913006205CB23: SYNTHETIC_TEST_STEP-3C1913006205CB23
          id_SYNTHETIC_TEST_STEP_7D0DC1A05D55506A: SYNTHETIC_TEST_STEP-7D0DC1A05D55506A
          id_SYNTHETIC_TEST_STEP_7D2AAA00BDE55F34: SYNTHETIC_TEST_STEP-7D2AAA00BDE55F34
          id_SYNTHETIC_TEST_STEP_7E56D6B5FDA1FE82: SYNTHETIC_TEST_STEP-7E56D6B5FDA1FE82
          id_SYNTHETIC_TEST_STEP_51103C3DF6A3672D: SYNTHETIC_TEST_STEP-51103C3DF6A3672D
          id_SYNTHETIC_TEST_STEP_804795ACA122892A: SYNTHETIC_TEST_STEP-804795ACA122892A
          id_SYNTHETIC_TEST_STEP_5133046FFB3A998E: SYNTHETIC_TEST_STEP-5133046FFB3A998E
          id_SYNTHETIC_TEST_STEP_BD86F90538A7CC4B: SYNTHETIC_TEST_STEP-BD86F90538A7CC4B
          id_SYNTHETIC_TEST_STEP_E7FC40FE9A2F6E50: SYNTHETIC_TEST_STEP-E7FC40FE9A2F6E50
          id_SYNTHETIC_TEST_STEP_F8D1CE7FC963A318: SYNTHETIC_TEST_STEP-F8D1CE7FC963A318
    template: synthetic.json
    skip: false
  type:
    api: synthetic-monitor
- id: synthetic-gitlab
  config:
    name: gitlab
    parameters:
      gitlabUrl:
        type: environment
        name: GITLAB_EXTERNAL_ENDPOINT
      gitlabHttpsUrl:
        type: environment
        name: GITLAB_HTTPS_URL
      gitlabToken:
        type: environment
        name: GITLAB_PASSWORD
      location: 
        configId: SYNTHETIC_LOCATION-1
        configType: synthetic-location
        property: id
        type: reference
      extractedIDs:
        type: value
        value:
          id_GEOLOCATION_0DF9A0E1095A5A62: GEOLOCATION-0DF9A0E1095A5A62
          id_SYNTHETIC_TEST_STEP_5CF79101259EC836: SYNTHETIC_TEST_STEP-5CF79101259EC836
          id_SYNTHETIC_TEST_STEP_9DEF25F1DC5E7D37: SYNTHETIC_TEST_STEP-9DEF25F1DC5E7D37
          id_SYNTHETIC_TEST_STEP_487EB6EE2CB4EEEB: SYNTHETIC_TEST_STEP-487EB6EE2CB4EEEB
          id_SYNTHETIC_TEST_STEP_2180F53B8CA74ABD: SYNTHETIC_TEST_STEP-2180F53B8CA74ABD
          id_SYNTHETIC_TEST_STEP_091519792A2B5EBA: SYNTHETIC_TEST_STEP-091519792A2B5EBA
          id_SYNTHETIC_TEST_STEP_60935598315E9984: SYNTHETIC_TEST_STEP-60935598315E9984
          id_SYNTHETIC_TEST_STEP_6AD1A7AA604FDD4D: SYNTHETIC_TEST_STEP-6AD1A7AA604FDD4D
          id_SYNTHETIC_TEST_STEP_A264A6EA3C85AEE6: SYNTHETIC_TEST_STEP-A264A6EA3C85AEE6
          id_SYNTHETIC_TEST_STEP_B1314963B4DA57D7: SYNTHETIC_TEST_STEP-B1314963B4DA57D7
          id_SYNTHETIC_TEST_STEP_CD9AD7A99C80A60F: SYNTHETIC_TEST_STEP-CD9AD7A99C80A60F
          id_SYNTHETIC_TEST_STEP_D15E7DB152A27630: SYNTHETIC_TEST_STEP-D15E7DB152A27630
          id_SYNTHETIC_TEST_STEP_E5C619684D0DDFA0: SYNTHETIC_TEST_STEP-E5C619684D0DDFA0
          id_SYNTHETIC_TEST_STEP_E4223284EABE1FD8: SYNTHETIC_TEST_STEP-E4223284EABE1FD8
    template: gitlab.json
    skip: false
  type:
    api: synthetic-monitor
